name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use a compatible Node.js version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/USERNAME/REPOSITORY_NAME.git main:gh-pages
